
package com.test.csf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoServiceImpl", targetNamespace = "http://service.cxf.xt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geeCxfMsg", targetNamespace = "http://service.cxf.xt.com/", className = "com.test.csf.GeeCxfMsg")
    @ResponseWrapper(localName = "geeCxfMsgResponse", targetNamespace = "http://service.cxf.xt.com/", className = "com.test.csf.GeeCxfMsgResponse")
    @Action(input = "http://service.cxf.xt.com/DemoServiceImpl/geeCxfMsgRequest", output = "http://service.cxf.xt.com/DemoServiceImpl/geeCxfMsgResponse")
    public String geeCxfMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
