
package com.test.csf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoServiceImplService", targetNamespace = "http://service.cxf.xt.com/", wsdlLocation = "http://localhost:9999/javaws/xtkj?wsdl")
public class DemoServiceImplService
    extends Service
{

    private final static URL DEMOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DEMOSERVICEIMPLSERVICE_QNAME = new QName("http://service.cxf.xt.com/", "DemoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/javaws/xtkj?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DEMOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DemoServiceImplService() {
        super(__getWsdlLocation(), DEMOSERVICEIMPLSERVICE_QNAME);
    }

    public DemoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOSERVICEIMPLSERVICE_QNAME, features);
    }

    public DemoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DEMOSERVICEIMPLSERVICE_QNAME);
    }

    public DemoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOSERVICEIMPLSERVICE_QNAME, features);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoServiceImpl
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public DemoServiceImpl getDemoServiceImplPort() {
        return super.getPort(new QName("http://service.cxf.xt.com/", "DemoServiceImplPort"), DemoServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoServiceImpl
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public DemoServiceImpl getDemoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf.xt.com/", "DemoServiceImplPort"), DemoServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DEMOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DEMOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
